### ISSUE TITLE
doesnt like to download discog 

### ISSUE THREAD

**Issue by DSMOS** [Otiel/BandcampDownloader#139]
[BandcampDownloader.log](https://github.com/Otiel/BandcampDownloader/files/4537362/BandcampDownloader.log)
it doesn't like flobots i guess, happens every time

**Comment by Otiel** [comment]
Thanks for reporting this!

**Comment by Otiel** [comment]
Sorry for the delay...

I cannot reproduce this. Does it still happen with this artist?

**Comment by Otiel** [comment]
Sorry for the delay...

It looks like [this track](https://flobots.bandcamp.com/track/hurqalya-postlude) was downloaded twice, which caused the error (bug tracked in #103), but I'm not seeing why it could have made the download twice in your case.

Do you know if this artist discrography has changed since you reported this issue?

**Comment by DSMOS** [comment]
It downloads fine now, thanks for your hard work!!

**Comment by Otiel** [comment]
Alright, feel free to re-open this issue if you get the bug once more!
