### ISSUE TITLE
It downloads the first and the last track

### ISSUE THREAD

**Issue by glebanych** [Otiel/BandcampDownloader#23]
Title says it all. I tried downloading full discography or albums separetely, no luck. It downloads the first and the last track, all tracks in between are 0 byte files.
![image](https://cloud.githubusercontent.com/assets/9075322/23294900/70213a8a-fa76-11e6-8b46-c63f59c6b504.png)

**Comment by Otiel** [comment]
I'm assume this is a case of the anti-spam mechanism at Bandcamp. The fact that only the first and last track are downloaded is purely coincidental, only a few track are downloaded before Bandcamp blocks you.

Can you try adding these lines to your settings file (`BcDlSettings.json`)?

```
"DownloadMaxTries": 7
"DownloadRetryCooldown": 0.2
"DownloadRetryExponential": 2.0
```

Check the [wiki](https://github.com/Otiel/BandcampDownloader/wiki/Settings-file) for more info.

**Comment by glebanych** [comment]
After editing it seems to work better, but still not very well (half of the tracks are skipped). Any suggestions?
![image](https://cloud.githubusercontent.com/assets/9075322/23302065/c0534f2e-fa95-11e6-9a3e-205556001b70.png)

**Comment by Otiel** [comment]
This seems to be really dependent on your connection and interaction with Bandcamp servers, so you'll have to play with those three values in order to find a good solution.

Try setting `"DownloadRetryExponential": 3.0`. If that doesn't work, try `4.0`.

Are you using Bandcamp in any other way in the same time? Listening to music, trying to download another album? Are you alone on your Internet connection?

**Comment by glebanych** [comment]
Ok, after setting `"DownloadRetryExponential"` to `4.0` it finally works, at least when I try to download albums separetely :)
And no, i was not using bandcamp in any other way and my connection is fine.
Thanks for help and great tool!

**Comment by Otiel** [comment]
Great, you are welcome! Let me know if you get any more trouble.
