### ISSUE TITLE
Customize file naming scheme

### ISSUE THREAD

**Issue by TadEro** [Otiel/BandcampDownloader#41]
Hello, I just downloaded this and holy crap, it's amazing!!
Except for only one thing... is there a way for the files to download as "Play time" instead of "02 glitched puppet - Play time"? If there's one, please tell me. If not, can you *please* add it? It would make me to completely love your program!

**Comment by Otiel** [comment]
Hi, thanks!

Currently there's no way to change the files naming scheme, but I can implement something to customize it. I'm afraid I won't have time before October though, so you'll have to be patient. Or look into file renaming software. :)

**Comment by TadEro** [comment]
Well, I can live with that. Thanks for responding and for the future implement!

**Comment by Otiel** [comment]
Oh gosh, I'm dumb. 😢 

It has already been implemented since v0.1.7.0, following #17. I had forgot about it, sorry.

You just have to edit your settings file and change the following:
`"FilenameFormat": "{tracknum} {artist} - {title}.mp3"`
to 
`"FilenameFormat": "{title}.mp3"`.

There is currently no way to change it directly in the interface, but I'll do something about this in the future. Until then, you'll have to play with the settings file. 😄

**Comment by TadEro** [comment]
Settings file? Where can I found it?

**Comment by Otiel** [comment]
Next to the *exe* file. If it doesn't exist yet, you can create it by clicking to the "save settings" button.

You can find more info [here](https://github.com/Otiel/BandcampDownloader/wiki/Settings-file).
