### ISSUE TITLE
Save lyrics in tags

### ISSUE THREAD

**Issue by quicly** [Otiel/BandcampDownloader#42]
Hi, some bands put song lyrics on bandcamp page and it would be so great if app could save them in the tags. Don't know how hard technicaly to do this, but it would be so much help for non-english speakers

**Comment by Otiel** [comment]
Can you share an example?

**Comment by quicly** [comment]
https://weneverlearnedtolive.bandcamp.com/album/silently-i-threw-them-skyward
For example
You can click "lyrics" to the left from song title

**Comment by Otiel** [comment]
That's too bad those lyrics are not provided in [*lrc* format](https://en.wikipedia.org/wiki/LRC_(file_format)), that would have been nice. I guess I can try to save the lyrics in a *txt* file at best, is this what you are looking for? One file per song, named *song.txt* containing the song's lyrics?

**Comment by quicly** [comment]
I meant more like saving it in the mp3tags.
So i can, for example, see it on my phone screen when the song is playing
Right now i have to copy all the lyrics from bandcamp manually...

**Comment by Otiel** [comment]
That makes sense, good suggestion. I'll have a look at it.

**Comment by ajsnyde** [comment]
@quicly @Otiel  This functionality should be added. Can we close this issue?

**Comment by Otiel** [comment]
I prefer to keep this issue opened until I release a new version offering the functionality. This allows people to find the feature request when searching through opened issues.

I still have to find the time to make the new release, but I'd like to make improvements before in order to support the download of lyrics from album pages as well (only track pages are currently supported since https://github.com/Otiel/BandcampDownloader/pull/52).

**Comment by ajsnyde** [comment]
@Otiel Check this PR: https://github.com/Otiel/BandcampDownloader/pull/59

**Comment by Otiel** [comment]
Released in [0.2.0.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.0.0)
