### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Botanistt** [Otiel/BandcampDownloader#53]
Absolutely stunning! Works perfectly without any flaws. Thank you so much.

**Comment by Otiel** [comment]
Thanks for the kind words. 👍

**Comment by Botanistt** [comment]
Soundcloud version coming up soon? 😅

**Comment by Otiel** [comment]
As a matter of fact I already did [one](https://github.com/Otiel/SoundCloudDownloader) a few years ago, but it completely broke (don't even try it 😄) when they retired the "Classic SoundCloud". That one, if you knew it:

![image](https://user-images.githubusercontent.com/3851902/37979927-225db150-31ea-11e8-8fcb-f88ac051d099.png)

Since then, I didn't find the time to update it to match the new website. 😑
