### ISSUE TITLE
Failure to download full songs & crashes

### ISSUE THREAD

**Issue by justinwzig** [Otiel/BandcampDownloader#8]
I've been looking for a suitable utility forever now and this was particularly promising but it seems to have problems with finishing downloading - every time I try to download an album some songs show up just fine and it's all good until it starts showing errors (orange) about that attempt to download the song failing and then it crashes. Is this a side-effect of the antispam thing in the other thread? It happened to me after I waited overnight and the first time I ever used the program. I have a low speed but consistent internet connection and don't use a proxy.

Here's a badly made but effective gif: 
![gif](https://cloud.githubusercontent.com/assets/4504400/19022066/e5990c4c-8894-11e6-9818-d69268738d8d.gif)"

It's also worth noting that some of the songs it downloads (they show up as downloading.... in the console) are cut off - I have a bunch of 30s songs in here when band camp reports they are above 2:00.

**Comment by justinwzig** [comment]
Update: @beppe9000's release seems to have more success although it does occasionally hang. I'll keep using that and see if it's more consistent.

**Comment by Otiel** [comment]
Yes I believe that is due to the anti-spam possible mechanism that Bandcamp uses. Since this album is quite long (72 tracks), that could be why you've seen the anti-spam activated on your first use of BandcampDownloader. Unfortunately, I have no idea on how to work around that. Did you try with other albums - with a number of tracks more usual (10-20)? Are you seeing errors as well?

From what I can see, @beppe9000 didn't commit any improvement to his repo since he provided a fix. I included that fix in my repo, so there shouldn't be any difference in the two versions - at least on the network part (I made some changes since but they shouldn't impact the behavior you see here). The fact that you seem to have more success with his version is in my opinion, purely coincidental (but please keep using his version if it gives you more luck :smile: )

If Google Drive is setting locks on files when uploading, that can explain why you end up with 30sec songs.

**Comment by beppe9000** [comment]
I think it is worth saying that jDownloader does support downloading from Bandcamp, and given its mature infrastructure I am preferring it to BandcampDownloader.

**Comment by Otiel** [comment]
Thanks for the info.

**Comment by deadmans96** [comment]
why JDownloader and IDM can identify the download link for such a song !?

**Comment by beppe9000** [comment]
> why JDownloader and IDM can identify the download link for such a song !?
you should inspect the html code and realize the download links are ther in plain sight

**Comment by deadmans96** [comment]
@beppe9000 so is't possible to try to fix the downloading error by using IDM method !?

**Comment by Otiel** [comment]
@deadmans96 I'm not sure what you're asking. It may be possible to "fix" this error, but unfortunately I won't have the time to look into that to modify the code of *BandcampDownloader*. But you're welcome to use IDM or JDownloader if they work better.

**Comment by beppe9000** [comment]
@deadmans96 Considering what Otiel said before, the fix should be either limiting the track download rate or enforcing an exclusive file lock while MP3s are being downloaded. I switched to JDownloader as I was already using it for other downloads, so I don't plan to fix this, as it may require some time (that I do not have).
